### ISSUE TITLE
Proposal for documents project of NutsDB which based Docusaurus

### ISSUE THREAD

**Issue by TremblingV5** [nutsdb/nutsdb#557]
# Proposal for documents project of NutsDB which based Docusaurus

[TOC]

## Overview

Now I have create preview site of nutsdb on this site: https://tremblingv5.github.io/nutsdb/

Details can be found here: https://github.com/TremblingV5/nutsdb/tree/docs

Framework：https://github.com/facebook/docusaurus

This solution about create a documents site for NutsDB is rely on `Node 18+`. So we must prepare for a node environment if we want to run it locally. Run this project is just like run a FE site which is pure static.

Advantages:

- Easy to use
- We can customize it easily

## How to start

Same with other node projects, there's a `package.json` on the root directory of this project. In this file, there are many scripts. We can use `yarn install && yarn start` to run it good locally.

### Navigation bar

- Documents（multi-pages）
- About page（single page）
- Blog（single page）
- Community（single page）
- Solutions（single-page）

### Create a new page

`Page`  just like the "About", "Community" and "Solutions" above which means a single page. We can create a markdown file or a react file on `src/pages` to create a new page.

If the created file named with `test.md`, then we can open it via `http://BASE/test`

### Create new documents

`Documents` means a group of pages. In the test site, `Tuorial` page use this mode. The side bar is a directory of whole documents. We can use 2 mode to manage it:

1. Auto generate
2. Manually: in `sidebars.ts`, by using `typescript`(I'd like this)

Manually, we can create a documents follow this steps:

1. Create directory and files
2. Add something in the created files
3. Add these code in the `items` of `sidebars.ts`

```json
{
	type: 'doc',
    id: 'path/file' // 不包含".md"的Markdown文件路径
}

```

If we want insert a picture, we can put it to `static/img`. Then we can import it in files.

### Multiple versions

Refer：[https://tutorial.docusaurus.io/docs/tutorial-extras/manage-docs-versions/](https://tutorial.docusaurus.io/docs/tutorial-extras/manage-docs-versions/)

### Multiple langs

On `i18n/en/docusaurus-plugin-content-docs/current` we can create files with the same directories with the root path. And it will be auto loaded.

### Deploy to github pages

The official work flow files as following:

```yaml
name: Deploy Docs to Github Pages

on:
  pull_request:
    branches:
      - docs
  push:
    branches:
      - docs

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # 你可以用自己的用户信息替换它们。
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
```

We need to generate a Github PAT and configure it for NutsDB

Indeed, this work flow will use `yarn` to build from `docs` branch, then publish the built files to `gh-pages` branch. So we need configure the source of Github Pages with `gh-pages`
